
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const doc = new PDFDocument({ margin: 50 });
const filename = 'CRM_Gated_Compliance_Audit_Guide.pdf';
const outputPath = path.join(process.cwd(), filename);

doc.pipe(fs.createWriteStream(outputPath));

// Header
doc.fillColor('#4F46E5').fontSize(24).font('Helvetica-Bold').text('CRM Gated Compliance', { align: 'center' });
doc.fontSize(16).fillColor('#1E293B').text('Technical Audit & Verification Guide', { align: 'center' });
doc.moveDown(2);

// Section 1: Core Logic
doc.fillColor('#1E293B').fontSize(18).font('Helvetica-Bold').text('1. Core Intelligence Logic');
doc.fontSize(12).font('Helvetica').text('The compliance engine operates on a Gated Logic principle. In the file src/app/actions/crm/target-compliance.ts, the system performs a multi-phase check:', { align: 'justify' });
doc.moveDown(0.5);
doc.list([
    'Phase 1: Real-time Metric Analysis - Aggregates lead and deal data for the assignee.',
    'Phase 2: Milestone Validation - Compares current achievement against milestone gates.',
    'Phase 3: Blocking Enforcement - If a milestone is marked "is_blocking" and the deadline is passed without reaching the goal, the entire mission is terminated (Failed).'
], { bulletRadius: 3 });
doc.moveDown(1.5);

// Section 2: How to Verify (Stress Test)
doc.fillColor('#1E293B').fontSize(18).font('Helvetica-Bold').text('2. Step-by-Step Verification Protocol');
doc.fontSize(12).font('Helvetica').text('To verify that blocking is functioning correctly, follow this stress test:', { align: 'justify' });
doc.moveDown(0.5);

doc.font('Helvetica-Bold').text('Step A: Create a "Fail" Scenario');
doc.font('Helvetica').text('1. Navigate to CRM > Targets > Initialize Target.');
doc.text('2. Set the Period End to a date in the future.');
doc.text('3. Create a Milestone with Metric: "Deals Created", Target: 5.');
doc.text('4. Set the Milestone Deadline to YESTERDAY.');
doc.text('5. Toggle "is_blocking" to YES (Blue Switch).');
doc.text('6. Click Synchronize Mission.');
doc.moveDown(0.5);

doc.font('Helvetica-Bold').text('Step B: Trigger Intelligence Sync');
doc.font('Helvetica').text('1. Go to Targets > Strategic Dashboard (Management).');
doc.text('2. Click "Synchronize Team Data".');
doc.text('3. The system will process the expired gate.');
doc.moveDown(0.5);

doc.font('Helvetica-Bold').text('Step C: Verify Observation');
doc.font('Helvetica').text('1. Back in the Targets main list, the status should now be RED ("FAILED").');
doc.text('2. The Progress Bar will indicate non-compliance.');
doc.moveDown(1.5);

// Section 3: Strategic Impact
doc.fillColor('#1E293B').fontSize(18).font('Helvetica-Bold').text('3. Strategic Impact for Salesmen');
doc.fontSize(12).font('Helvetica').text('When a Salesman fails a blocking milestone:', { align: 'justify' });
doc.moveDown(0.5);
doc.list([
    'They are flagged on the Admin Management Roster as an "At-Risk Asset".',
    'Total team revenue synthesis is adjusted to exclude their failed forecast.',
    'The mission cannot be resurrected without manager intervention (Edit/Update).'
], { bulletRadius: 3 });

// Footer
doc.moveDown(4);
doc.fontSize(10).fillColor('#94A3B8').text('Generated by Antigravity AI Engine | System Version 2035-HMS-SAAS-ERP', { align: 'center' });

doc.end();

console.log(`PDF generated successfully at: ${outputPath}`);
