INSERT INTO countries (iso2, iso3, name, flag, region, is_active) VALUES
('AF', 'AFG', 'Afghanistan', '🇦🇫', 'Asia', true),
('AL', 'ALB', 'Albania', '🇦🇱', 'Europe', true),
('DZ', 'DZA', 'Algeria', '🇩🇿', 'Africa', true),
('AS', 'ASM', 'American Samoa', '🇦🇸', 'Oceania', true),
('AD', 'AND', 'Andorra', '🇦🇩', 'Europe', true),
('AO', 'AGO', 'Angola', '🇦🇴', 'Africa', true),
('AI', 'AIA', 'Anguilla', '🇦🇮', 'Americas', true),
('AQ', 'ATA', 'Antarctica', '🇦🇶', 'Polar', true),
('AG', 'ATG', 'Antigua and Barbuda', '🇦🇬', 'Americas', true),
('AR', 'ARG', 'Argentina', '🇦🇷', 'Americas', true),
('AM', 'ARM', 'Armenia', '🇦🇲', 'Asia', true),
('AW', 'ABW', 'Aruba', '🇦🇼', 'Americas', true),
('AU', 'AUS', 'Australia', '🇦🇺', 'Oceania', true),
('AT', 'AUT', 'Austria', '🇦🇹', 'Europe', true),
('AZ', 'AZE', 'Azerbaijan', '🇦🇿', 'Asia', true),
('BS', 'BHS', 'Bahamas', '🇧🇸', 'Americas', true),
('BH', 'BHR', 'Bahrain', '🇧🇭', 'Asia', true),
('BD', 'BGD', 'Bangladesh', '🇧🇩', 'Asia', true),
('BB', 'BRB', 'Barbados', '🇧🇧', 'Americas', true),
('BY', 'BLR', 'Belarus', '🇧🇾', 'Europe', true),
('BE', 'BEL', 'Belgium', '🇧🇪', 'Europe', true),
('BZ', 'BLZ', 'Belize', '🇧🇿', 'Americas', true),
('BJ', 'BEN', 'Benin', '🇧🇯', 'Africa', true),
('BM', 'BMU', 'Bermuda', '🇧🇲', 'Americas', true),
('BT', 'BTN', 'Bhutan', '🇧🇹', 'Asia', true),
('BO', 'BOL', 'Bolivia', '🇧🇴', 'Americas', true),
('BA', 'BIH', 'Bosnia and Herzegovina', '🇧🇦', 'Europe', true),
('BW', 'BWA', 'Botswana', '🇧🇼', 'Africa', true),
('BR', 'BRA', 'Brazil', '🇧🇷', 'Americas', true),
('IO', 'IOT', 'British Indian Ocean Territory', '🇮🇴', 'Africa', true),
('BN', 'BRN', 'Brunei Darussalam', '🇧🇳', 'Asia', true),
('BG', 'BGR', 'Bulgaria', '🇧🇬', 'Europe', true),
('BF', 'BFA', 'Burkina Faso', '🇧🇫', 'Africa', true),
('BI', 'BDI', 'Burundi', '🇧🇮', 'Africa', true),
('KH', 'KHM', 'Cambodia', '🇰🇭', 'Asia', true),
('CM', 'CMR', 'Cameroon', '🇨🇲', 'Africa', true),
('CA', 'CAN', 'Canada', '🇨🇦', 'Americas', true),
('CV', 'CPV', 'Cape Verde', '🇨🇻', 'Africa', true),
('KY', 'CYM', 'Cayman Islands', '🇰🇾', 'Americas', true),
('CF', 'CAF', 'Central African Republic', '🇨🇫', 'Africa', true),
('TD', 'TCD', 'Chad', '🇹🇩', 'Africa', true),
('CL', 'CHL', 'Chile', '🇨🇱', 'Americas', true),
('CN', 'CHN', 'China', '🇨🇳', 'Asia', true),
('CX', 'CXR', 'Christmas Island', '🇨🇽', 'Oceania', true),
('CC', 'CCK', 'Cocos (Keeling) Islands', '🇨🇨', 'Oceania', true),
('CO', 'COL', 'Colombia', '🇨🇴', 'Americas', true),
('KM', 'COM', 'Comoros', '🇰🇲', 'Africa', true),
('CG', 'COG', 'Congo', '🇨🇬', 'Africa', true),
('CD', 'COD', 'Congo, Democratic Republic of the', '🇨🇩', 'Africa', true),
('CK', 'COK', 'Cook Islands', '🇨🇰', 'Oceania', true),
('CR', 'CRI', 'Costa Rica', '🇨🇷', 'Americas', true),
('CI', 'CIV', 'Cote D''Ivoire', '🇨🇮', 'Africa', true),
('HR', 'HRV', 'Croatia', '🇭🇷', 'Europe', true),
('CU', 'CUB', 'Cuba', '🇨🇺', 'Americas', true),
('CY', 'CYP', 'Cyprus', '🇨🇾', 'Asia', true),
('CZ', 'CZE', 'Czech Republic', '🇨🇿', 'Europe', true),
('DK', 'DNK', 'Denmark', '🇩🇰', 'Europe', true),
('DJ', 'DJI', 'Djibouti', '🇩🇯', 'Africa', true),
('DM', 'DMA', 'Dominica', '🇩🇲', 'Americas', true),
('DO', 'DOM', 'Dominican Republic', '🇩🇴', 'Americas', true),
('EC', 'ECU', 'Ecuador', '🇪🇨', 'Americas', true),
('EG', 'EGY', 'Egypt', '🇪🇬', 'Africa', true),
('SV', 'SLV', 'El Salvador', '🇸🇻', 'Americas', true),
('GQ', 'GNQ', 'Equatorial Guinea', '🇬🇶', 'Africa', true),
('ER', 'ERI', 'Eritrea', '🇪🇷', 'Africa', true),
('EE', 'EST', 'Estonia', '🇪🇪', 'Europe', true),
('ET', 'ETH', 'Ethiopia', '🇪🇹', 'Africa', true),
('FK', 'FLK', 'Falkland Islands (Malvinas)', '🇫🇰', 'Americas', true),
('FO', 'FRO', 'Faroe Islands', '🇫🇴', 'Europe', true),
('FJ', 'FJI', 'Fiji', '🇫🇯', 'Oceania', true),
('FI', 'FIN', 'Finland', '🇫🇮', 'Europe', true),
('FR', 'FRA', 'France', '🇫🇷', 'Europe', true),
('GF', 'GUF', 'French Guiana', '🇬🇫', 'Americas', true),
('PF', 'PYF', 'French Polynesia', '🇵🇫', 'Oceania', true),
('GA', 'GAB', 'Gabon', '🇬🇦', 'Africa', true),
('GM', 'GMB', 'Gambia', '🇬🇲', 'Africa', true),
('GE', 'GEO', 'Georgia', '🇬🇪', 'Asia', true),
('DE', 'DEU', 'Germany', '🇩🇪', 'Europe', true),
('GH', 'GHA', 'Ghana', '🇬🇭', 'Africa', true),
('GI', 'GIB', 'Gibraltar', '🇬🇮', 'Europe', true),
('GR', 'GRC', 'Greece', '🇬🇷', 'Europe', true),
('GL', 'GRL', 'Greenland', '🇬🇱', 'Americas', true),
('GD', 'GRD', 'Grenada', '🇬🇩', 'Americas', true),
('GP', 'GLP', 'Guadeloupe', '🇬🇵', 'Americas', true),
('GU', 'GUM', 'Guam', '🇬🇺', 'Oceania', true),
('GT', 'GTM', 'Guatemala', '🇬🇹', 'Americas', true),
('GN', 'GIN', 'Guinea', '🇬🇳', 'Africa', true),
('GW', 'GNB', 'Guinea-Bissau', '🇬🇼', 'Africa', true),
('GY', 'GUY', 'Guyana', '🇬🇾', 'Americas', true),
('HT', 'HTI', 'Haiti', '🇭🇹', 'Americas', true),
('HN', 'HND', 'Honduras', '🇭🇳', 'Americas', true),
('HK', 'HKG', 'Hong Kong', '🇭🇰', 'Asia', true),
('HU', 'HUN', 'Hungary', '🇭🇺', 'Europe', true),
('IS', 'ISL', 'Iceland', '🇮🇸', 'Europe', true),
('IN', 'IND', 'India', '🇮🇳', 'Asia', true),
('ID', 'IDN', 'Indonesia', '🇮🇩', 'Asia', true),
('IR', 'IRN', 'Iran, Islamic Republic of', '🇮🇷', 'Asia', true),
('IQ', 'IRQ', 'Iraq', '🇮🇶', 'Asia', true),
('IE', 'IRL', 'Ireland', '🇮🇪', 'Europe', true),
('IL', 'ISR', 'Israel', '🇮🇱', 'Asia', true),
('IT', 'ITA', 'Italy', '🇮🇹', 'Europe', true),
('JM', 'JAM', 'Jamaica', '🇯🇲', 'Americas', true),
('JP', 'JPN', 'Japan', '🇯🇵', 'Asia', true),
('JO', 'JOR', 'Jordan', '🇯🇴', 'Asia', true),
('KZ', 'KAZ', 'Kazakhstan', '🇰🇿', 'Asia', true),
('KE', 'KEN', 'Kenya', '🇰🇪', 'Africa', true),
('KI', 'KIR', 'Kiribati', '🇰🇮', 'Oceania', true),
('KP', 'PRK', 'Korea, Democratic People''s Republic of', '🇰🇵', 'Asia', true),
('KR', 'KOR', 'Korea, Republic of', '🇰🇷', 'Asia', true),
('KW', 'KWT', 'Kuwait', '🇰🇼', 'Asia', true),
('KG', 'KGZ', 'Kyrgyzstan', '🇰🇬', 'Asia', true),
('LA', 'LAO', 'Lao People''s Democratic Republic', '🇱🇦', 'Asia', true),
('LV', 'LVA', 'Latvia', '🇱🇻', 'Europe', true),
('LB', 'LBN', 'Lebanon', '🇱🇧', 'Asia', true),
('LS', 'LSO', 'Lesotho', '🇱🇸', 'Africa', true),
('LR', 'LBR', 'Liberia', '🇱🇷', 'Africa', true),
('LY', 'LBY', 'Libyan Arab Jamahiriya', '🇱🇾', 'Africa', true),
('LI', 'LIE', 'Liechtenstein', '🇱🇮', 'Europe', true),
('LT', 'LTU', 'Lithuania', '🇱🇹', 'Europe', true),
('LU', 'LUX', 'Luxembourg', '🇱🇺', 'Europe', true),
('MO', 'MAC', 'Macao', '🇲🇴', 'Asia', true),
('MK', 'MKD', 'Macedonia, the Former Yugoslav Republic of', '🇲🇰', 'Europe', true),
('MG', 'MDG', 'Madagascar', '🇲🇬', 'Africa', true),
('MW', 'MWI', 'Malawi', '🇲🇼', 'Africa', true),
('MY', 'MYS', 'Malaysia', '🇲🇾', 'Asia', true),
('MV', 'MDV', 'Maldives', '🇲🇻', 'Asia', true),
('ML', 'MLI', 'Mali', '🇲🇱', 'Africa', true),
('MT', 'MLT', 'Malta', '🇲🇹', 'Europe', true),
('MH', 'MHL', 'Marshall Islands', '🇲🇭', 'Oceania', true),
('MQ', 'MTQ', 'Martinique', '🇲🇶', 'Americas', true),
('MR', 'MRT', 'Mauritania', '🇲🇷', 'Africa', true),
('MU', 'MUS', 'Mauritius', '🇲🇺', 'Africa', true),
('YT', 'MYT', 'Mayotte', '🇾🇹', 'Africa', true),
('MX', 'MEX', 'Mexico', '🇲🇽', 'Americas', true),
('FM', 'FSM', 'Micronesia, Federated States of', '🇫🇲', 'Oceania', true),
('MD', 'MDA', 'Moldova, Republic of', '🇲🇩', 'Europe', true),
('MC', 'MCO', 'Monaco', '🇲🇨', 'Europe', true),
('MN', 'MNG', 'Mongolia', '🇲🇳', 'Asia', true),
('MS', 'MSR', 'Montserrat', '🇲🇸', 'Americas', true),
('MA', 'MAR', 'Morocco', '🇲🇦', 'Africa', true),
('MZ', 'MOZ', 'Mozambique', '🇲🇿', 'Africa', true),
('MM', 'MMR', 'Myanmar', '🇲🇲', 'Asia', true),
('NA', 'NAM', 'Namibia', '🇳🇦', 'Africa', true),
('NR', 'NRU', 'Nauru', '🇳🇷', 'Oceania', true),
('NP', 'NPL', 'Nepal', '🇳🇵', 'Asia', true),
('NL', 'NLD', 'Netherlands', '🇳🇱', 'Europe', true),
('AN', 'ANT', 'Netherlands Antilles', '🇳🇱', 'Americas', true),
('NC', 'NCL', 'New Caledonia', '🇳🇨', 'Oceania', true),
('NZ', 'NZL', 'New Zealand', '🇳🇿', 'Oceania', true),
('NI', 'NIC', 'Nicaragua', '🇳🇮', 'Americas', true),
('NE', 'NER', 'Niger', '🇳🇪', 'Africa', true),
('NG', 'NGA', 'Nigeria', '🇳🇬', 'Africa', true),
('NU', 'NIU', 'Niue', '🇳🇺', 'Oceania', true),
('NF', 'NFK', 'Norfolk Island', '🇳🇫', 'Oceania', true),
('MP', 'MNP', 'Northern Mariana Islands', '🇲🇵', 'Oceania', true),
('NO', 'NOR', 'Norway', '🇳🇴', 'Europe', true),
('OM', 'OMN', 'Oman', '🇴🇲', 'Asia', true),
('PK', 'PAK', 'Pakistan', '🇵🇰', 'Asia', true),
('PW', 'PLW', 'Palau', '🇵🇼', 'Oceania', true),
('PS', 'PSE', 'Palestinian Territory, Occupied', '🇵🇸', 'Asia', true),
('PA', 'PAN', 'Panama', '🇵🇦', 'Americas', true),
('PG', 'PNG', 'Papua New Guinea', '🇵🇬', 'Oceania', true),
('PY', 'PRY', 'Paraguay', '🇵🇾', 'Americas', true),
('PE', 'PER', 'Peru', '🇵🇪', 'Americas', true),
('PH', 'PHL', 'Philippines', '🇵🇭', 'Asia', true),
('PN', 'PCN', 'Pitcairn', '🇵🇳', 'Oceania', true),
('PL', 'POL', 'Poland', '🇵🇱', 'Europe', true),
('PT', 'PRT', 'Portugal', '🇵🇹', 'Europe', true),
('PR', 'PRI', 'Puerto Rico', '🇵🇷', 'Americas', true),
('QA', 'QAT', 'Qatar', '🇶🇦', 'Asia', true),
('RE', 'REU', 'Reunion', '🇷🇪', 'Africa', true),
('RO', 'ROM', 'Romania', '🇷🇴', 'Europe', true),
('RU', 'RUS', 'Russian Federation', '🇷🇺', 'Europe', true),
('RW', 'RWA', 'Rwanda', '🇷🇼', 'Africa', true),
('SH', 'SHN', 'Saint Helena', '🇸🇭', 'Africa', true),
('KN', 'KNA', 'Saint Kitts and Nevis', '🇰🇳', 'Americas', true),
('LC', 'LCA', 'Saint Lucia', '🇱🇨', 'Americas', true),
('PM', 'SPM', 'Saint Pierre and Miquelon', '🇵🇲', 'Americas', true),
('VC', 'VCT', 'Saint Vincent and the Grenadines', '🇻🇨', 'Americas', true),
('WS', 'WSM', 'Samoa', '🇼🇸', 'Oceania', true),
('SM', 'SMR', 'San Marino', '🇸🇲', 'Europe', true),
('ST', 'STP', 'Sao Tome and Principe', '🇸🇹', 'Africa', true),
('SA', 'SAU', 'Saudi Arabia', '🇸🇦', 'Asia', true),
('SN', 'SEN', 'Senegal', '🇸🇳', 'Africa', true),
('CS', 'SCG', 'Serbia and Montenegro', '🇷🇸', 'Europe', true),
('SC', 'SYC', 'Seychelles', '🇸🇨', 'Africa', true),
('SL', 'SLE', 'Sierra Leone', '🇸🇱', 'Africa', true),
('SG', 'SGP', 'Singapore', '🇸🇬', 'Asia', true),
('SK', 'SVK', 'Slovakia', '🇸🇰', 'Europe', true),
('SI', 'SVN', 'Slovenia', '🇸🇮', 'Europe', true),
('SB', 'SLB', 'Solomon Islands', '🇸🇧', 'Oceania', true),
('SO', 'SOM', 'Somalia', '🇸🇴', 'Africa', true),
('ZA', 'ZAF', 'South Africa', '🇿🇦', 'Africa', true),
('GS', 'SGS', 'South Georgia and the South Sandwich Islands', '🇬🇸', 'Americas', true),
('ES', 'ESP', 'Spain', '🇪🇸', 'Europe', true),
('LK', 'LKA', 'Sri Lanka', '🇱🇰', 'Asia', true),
('SD', 'SDN', 'Sudan', '🇸🇩', 'Africa', true),
('SR', 'SUR', 'Suriname', '🇸🇷', 'Americas', true),
('SJ', 'SJM', 'Svalbard and Jan Mayen', '🇸🇯', 'Europe', true),
('SZ', 'SWZ', 'Swaziland', '🇸🇿', 'Africa', true),
('SE', 'SWE', 'Sweden', '🇸🇪', 'Europe', true),
('CH', 'CHE', 'Switzerland', '🇨🇭', 'Europe', true),
('SY', 'SYR', 'Syrian Arab Republic', '🇸🇾', 'Asia', true),
('TW', 'TWN', 'Taiwan, Province of China', '🇹🇼', 'Asia', true),
('TJ', 'TJK', 'Tajikistan', '🇹🇯', 'Asia', true),
('TZ', 'TZA', 'Tanzania, United Republic of', '🇹🇿', 'Africa', true),
('TH', 'THA', 'Thailand', '🇹🇭', 'Asia', true),
('TL', 'TLS', 'Timor-Leste', '🇹🇱', 'Asia', true),
('TG', 'TGO', 'Togo', '🇹🇬', 'Africa', true),
('TK', 'TKL', 'Tokelau', '🇹🇰', 'Oceania', true),
('TO', 'TON', 'Tonga', '🇹🇴', 'Oceania', true),
('TT', 'TTO', 'Trinidad and Tobago', '🇹🇹', 'Americas', true),
('TN', 'TUN', 'Tunisia', '🇹🇳', 'Africa', true),
('TR', 'TUR', 'Turkey', '🇹🇷', 'Asia', true),
('TM', 'TKM', 'Turkmenistan', '🇹🇲', 'Asia', true),
('TC', 'TCA', 'Turks and Caicos Islands', '🇹🇨', 'Americas', true),
('TV', 'TUV', 'Tuvalu', '🇹🇻', 'Oceania', true),
('UG', 'UGA', 'Uganda', '🇺🇬', 'Africa', true),
('UA', 'UKR', 'Ukraine', '🇺🇦', 'Europe', true),
('AE', 'ARE', 'United Arab Emirates', '🇦🇪', 'Asia', true),
('GB', 'GBR', 'United Kingdom', '🇬🇧', 'Europe', true),
('US', 'USA', 'United States', '🇺🇸', 'Americas', true),
('UM', 'UMI', 'United States Minor Outlying Islands', '🇺🇸', 'Oceania', true),
('UY', 'URY', 'Uruguay', '🇺🇾', 'Americas', true),
('UZ', 'UZB', 'Uzbekistan', '🇺🇿', 'Asia', true),
('VU', 'VUT', 'Vanuatu', '🇻🇺', 'Oceania', true),
('VE', 'VEN', 'Venezuela', '🇻🇪', 'Americas', true),
('VN', 'VNM', 'Viet Nam', '🇻🇳', 'Asia', true),
('VG', 'VGB', 'Virgin Islands, British', '🇻🇬', 'Americas', true),
('VI', 'VIR', 'Virgin Islands, U.S.', '🇻-🇮', 'Americas', true),
('WF', 'WLF', 'Wallis and Futuna', '🇼🇫', 'Oceania', true),
('EH', 'ESH', 'Western Sahara', '🇪🇭', 'Africa', true),
('YE', 'YEM', 'Yemen', '🇾🇪', 'Asia', true),
('ZM', 'ZMB', 'Zambia', '🇿🇲', 'Africa', true),
('ZW', 'ZWE', 'Zimbabwe', '🇿🇼', 'Africa', true)
ON CONFLICT (iso2) DO NOTHING;
