interface PremiumPrintFooterProps {
    note?: string;
    showSignature?: boolean;
    signatureLabel?: string;
    systemInfo?: string;
}

export function PremiumPrintFooter({
    note = "Thank you for choosing our services. We value your trust.",
    showSignature = true,
    signatureLabel = "Authorized Signatory",
    systemInfo = "Generated by Cloud HMS Enterprise ERP"
}: PremiumPrintFooterProps) {
    return (
        <div className="mt-auto pt-12">
            <div className="grid grid-cols-2 gap-12 mb-12">
                <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 flex flex-col justify-center">
                    <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] mb-3">Terms & Conditions</h3>
                    <p className="text-[10px] text-slate-500 leading-relaxed italic font-medium">
                        {note}
                    </p>
                </div>

                {showSignature && (
                    <div className="flex flex-col items-center justify-end group">
                        <div className="h-20 w-56 border-b-2 border-slate-900 border-dashed mb-4 flex items-center justify-center italic text-slate-200 text-[10px] uppercase tracking-widest">
                            digital signature secure
                        </div>
                        <p className="text-[11px] font-black text-slate-900 uppercase tracking-[0.2em]">{signatureLabel}</p>
                        <p className="text-[9px] text-slate-400 font-bold mt-1 tracking-widest uppercase">Identity Verified</p>
                    </div>
                )}
            </div>

            <div className="pt-8 border-t border-slate-100 flex justify-between items-center text-[9px] text-slate-300 font-bold uppercase tracking-[0.3em]">
                <span>{systemInfo}</span>
                <span>{new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
            </div>
        </div>
    );
}
